sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        EemCUtIv1ojYu6z5nXCWnAKKEeoOYuHE4jpnuZ57zO6Yz1R/xiP+9MobWw3+ZmGKDMqv9XBeDSQfdsI2lBposCADS5Un1uOAZQTyBNbn2QWJ5wInFUvGBSidRAbaAXxXtWlW2o0qcwaPqyVGZcEMvcCdHrArdPW6DbUvPJwU0GyoISMRQGcnayhegJvTaXVGCmEaf6hHVr1Kvwcnc8VSFKhcnwERFJqZX6vXhK813JvTYNPU5JqrpZjs1yeQKdbQ/F+409jolffoNgUmoFTSv14ZN8GUoWriGqHbm8Cq7Vy2zsghoStW5PSBtqdS1C2vYFY4MwrRYSbk9AYqsp4sU23bCva4Ad2cLAu5R4zVG/KPIgtmVNfEOru7BzHAG635uPQ1iuP9RVeatkgpwGhDiPE5fB989hcc4xUiceeLJi/2m6237zvNRio96fRm4hmIXFUDMqOA4dr8XtIxRxVk8j0wJzGPZTsdhKW6RhUNxQ+A6cZgN0fFtdv7jcs10Jm2hNRMNc1oYp7vLZk9TuA1kcYJwab7irdTXduc4ZsIvAHjBciC5J6kXLk0q2P7gP1u4jbr6NAX9GbQlgZDZG7ukvur0l6YAkU9M1ehijZ3lenaU3nrYUYaclnLr4T9LJVMJlw+dq5IPY/oghbAQDxEIJGflmzu1nc4U7PPI6/cgBs=
    - secure: >-
        QMlugZa0M8aY8qWuEHloo6s6J9QDo2ZK9XJb57B4CRG6d8wHi/GK2miDV7tSk9+vRfJOi4BVZ360m3DNCbdOeh+cfW5ieprDSwd0unNQz/jZf6E0wHP83eKLlpsW/Y6lU8A0hU5WOGSboX2e+S/wL7B5pI03GI1Qh4EcAFLHk0OHCHe6e8g4pQ8edHaEbkWDJArqke+CSvAU2Duyx1VYfvfBbOWsp4tRQ1k9p11mm2z/zgm5/pf64UT1GdFxxPjK8Apyfv25o6sCJG0+xh8ZOF4HuQZW9iKIt9haWQpk/zJGK+sq61CplRePO3gbzqKUnXhJDI4yQgDShLvaDfv4WDfMy+hXPCFCF4RrnrD2jMwhn3czRrNfg4DI+YTymKgvf7+ldCVx+Mk6TFoUv5ZikIdRsaipDTot4oToV/qKXIHx02N5xRRT858yCEWNbESfJL9F6g1wRLRbpOnfFfIydwDXAQAz0EF+ITX8meyqMwt9dNIUnei4gDPYBLbBUYTcnogQU5d0MHvyfuyHXV0Uj3koQ1H3CcZqguSn9V5H4GaNjSdBSdbO3dpZm5O6CQOnb4y3YMzQEYRhWj6246/Ag+NDfXyUB055Dzzn8wadjZyeIPbhoGINxyirVH/ma01HSU0vh2iP1F+Gsg7Hvrs2aNmbD395ABrM358idbCQaVc=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
